import mongoose from 'mongoose';

const GenerationSessionSchema = new mongoose.Schema({
    sessionId: {
        type: String, // UUID generated by us or n8n
        required: true,
        unique: true,
        index: true
    },

    repoFullName: {
        type: String,
        required: true
    },

    status: {
        type: String,
        enum: [
            'GENERATING',      // Initial state, sent to n8n
            'CODE_CREATED',    // n8n returned files (code review phase)
            'PR_OPEN',         // User created PR (or n8n created it)
            'PR_MERGED',       // PR merged to main
            'CI_RUNNING',      // GitHub Actions triggered
            'COMPLETED',       // Pipeline success
            'FAILED'           // Something went wrong
        ],
        default: 'GENERATING'
    },

    generatedFiles: {
        type: Map, // e.g. "path/to/file": "content"
        of: String,
        default: {}
    },

    prUrl: {
        type: String
    },

    branchName: {
        type: String
    },

    ciStatus: {
        type: String, // from GitHub 'workflow_job' status
    },

    createdAt: {
        type: Date,
        default: Date.now
    },

    updatedAt: {
        type: Date,
        default: Date.now
    }
}, { timestamps: true });

export const GenerationSession = mongoose.model('GenerationSession', GenerationSessionSchema);
